backend:
  name: github
  repo: catuy/catuy.github.io  # Reemplaza con tu usuario y repositorio de GitHub
  branch: master  # O la rama que uses (main, master, etc.)
  auth_scope: repo  # Permisos necesarios
  site_domain: catuy/catuy.github.io  # Para desarrollo local
  # base_url:  catuy/catuy.github.io  # Para desarrollo local
  client_id: Ov23liZ0qzrw82lHZNR7  # Tu Client ID
  client_secret: 4776b6d5347f5b2091198fbc7ba3db0f729073b5  # Tu Client Secret

media_folder: "assets/blogimages"  # Carpeta donde se guardarán las imágenes subidas
public_folder: "/assets/blogimages"  # Ruta pública para acceder a las imágenes

collections:
  - name: "posts"  # Nombre de la colección (por ejemplo, para entradas de blog)
    label: "Posts"
    folder: "_posts"  # Carpeta donde se guardan los archivos
    create: true  # Permite crear nuevos archivos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Formato del nombre del archivo
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }